services:
  mywebsite:
    build: .
    container_name: mywebsite
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./My-Brain:/app/My-Brain
