services:
  mywebsite:
    build: .
    container_name: mywebsite
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./My-Brain:/app/My-Brain

  mcp-server:
    build: .
    container_name: mcp-server
    restart: always
    network_mode: "host"
    command: ["python", "mcp/server.py"]
    env_file:
      - .env
    volumes:
      - ./My-Brain:/app/My-Brain
