document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('orderForm'),stove=document.getElementById('addonStove'),modal=document.getElementById('orderModal');
 if(form) form.noValidate=true;
 const money=v=>`${Math.max(0,Math.round(Number(v)||0)).toLocaleString('vi-VN')}đ`;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const inputs=()=>[...document.querySelectorAll('.item-qty')];
 function summary(){const items=inputs().map(i=>({name:i.dataset.name||'Món',qty:Math.max(0,parseInt(i.value,10)||0),price:Math.max(0,parseInt(i.dataset.price,10)||0)})).filter(i=>i.qty);const subtotal=items.reduce((s,i)=>s+i.qty*i.price,0);const discount=subtotal?50000:0;const stoveFee=stove?.checked&&subtotal<399000?50000:0;const total=Math.max(0,subtotal+stoveFee-discount);const list=document.getElementById('summaryItemList');if(list)list.innerHTML=items.length?items.map(i=>`<div class="summary-line summary-item"><span>${esc(i.name)} × ${i.qty}<small>${money(i.price)} / món</small></span><strong>${money(i.qty*i.price)}</strong></div>`).join(''):'<p class="summary-empty">Chưa có món nào được chọn.</p>';const sub=document.getElementById('summarySubtotal');if(sub)sub.textContent=money(subtotal);const d=document.getElementById('summaryDiscount');if(d)d.textContent=discount?`-${money(discount)}`:'0đ';const f=document.getElementById('summaryStoveFee');if(f)f.textContent=stove?.checked?(stoveFee?money(stoveFee):'0đ (miễn phí)'):'Không mượn bếp';const t=document.getElementById('totalPrice');if(t)t.textContent=money(total);return{items,subtotal,discount,stoveFee,total};}
 function setQty(i,n){i.value=Math.max(0,n);const b=document.getElementById(`badge-${i.id}`);if(b){b.textContent=i.value;b.classList.toggle('has-count',n>0)}}
 const showToast=(message,type='error')=>{let toast=document.getElementById('ln-toast');if(!toast){toast=document.createElement('div');toast.id='ln-toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast)}toast.className=`ln-toast ln-toast-${type}`;toast.textContent=message;requestAnimationFrame(()=>toast.classList.add('is-visible'));clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove('is-visible'),5000)};
 const toastStyle=document.createElement('style');toastStyle.textContent='.ln-toast{position:fixed;top:20px;left:50%;z-index:3000;max-width:min(92vw,520px);padding:14px 20px;border-radius:14px;background:#3d2616;color:#f7f4ef;box-shadow:0 10px 30px rgba(61,38,22,.25);font:600 15px/1.5 "Plus Jakarta Sans",sans-serif;opacity:0;transform:translate(-50%,-18px);pointer-events:none;transition:opacity .25s ease,transform .25s ease}.ln-toast.is-visible{opacity:1;transform:translate(-50%,0)}.ln-toast-success{border-left:5px solid #d57a55}.ln-toast-error{border-left:5px solid #d57a55}@media(prefers-reduced-motion:reduce){.ln-toast{transition:none}}';document.head.appendChild(toastStyle);
 document.addEventListener('click',e=>{const b=e.target.closest('.btn-minus,.btn-plus');if(b){e.preventDefault();const i=document.getElementById(b.dataset.target);if(i){setQty(i,(parseInt(i.value,10)||0)+(b.classList.contains('btn-plus')?1:-1));summary()}return}const card=e.target.closest('.set-card');if(card&&!e.target.closest('button,input,a')){const i=card.querySelector('.item-qty');if(i){inputs().forEach(x=>{if(x!==i)setQty(x,0)});setQty(i,1);summary()}}});document.addEventListener('change',e=>{if(e.target.matches('.item-qty,#addonStove'))summary()});
 const close=()=>modal?.classList.remove('active');document.getElementById('closeModal')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});summary();if(!form)return;
 form.addEventListener('submit',async e=>{e.preventDefault();const value=id=>(document.getElementById(id)?.value||'').trim(),name=value('custName'),phone=value('custPhone'),email=value('custEmail'),address=value('custAddress'),s=summary();if(!name||!phone||!address)return showToast('Vui lòng điền họ tên, số điện thoại và địa chỉ.');if(!s.items.length)return showToast('Vui lòng chọn ít nhất một món hoặc một set.');const submit=form.querySelector('button[type="submit"]');if(submit)submit.disabled=true;try{const orderCode=`LN-${Math.floor(1000+Math.random()*9000)}`;const endpoint=new URL('/api/send-order',document.baseURI).toString();const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cust_name:name,cust_phone:phone,cust_email:email,cust_address:address,order_code:orderCode,items:s.items,stove_included:!!stove?.checked})}),result=await r.json().catch(()=>({}));if(!r.ok||!result.success)throw Error(result.error||`HTTP ${r.status}`);const displayedCode=result.order_code||result.orderId||orderCode;document.getElementById('modalName').textContent=name;document.getElementById('modalAddress').textContent=address;const codeElement=document.getElementById('modalOrderCode')||document.getElementById('orderCodeDisplay')||document.getElementById('orderCode');if(codeElement)codeElement.textContent=`Mã đơn hàng: ${displayedCode}`;modal?.classList.add('active')}catch(err){console.error('Send order error:',err);showToast('Xin lỗi, đơn hàng chưa được gửi. Vui lòng kiểm tra kết nối và thử lại sau.')}finally{if(submit)submit.disabled=false}})
});

(function() {
    var iframe = document.getElementById('survey-iframe');
    if (!iframe) return;
    var loadCount = 0;
    iframe.onload = function() {
      loadCount++;
      if (loadCount > 1) {
        iframe.style.height = '380px';
        iframe.scrollIntoView({ behavior: 'smooth', block: 'center' });
      }
    };
  })();
