document.addEventListener('DOMContentLoaded',()=>{
 const form=document.getElementById('orderForm'),stove=document.getElementById('addonStove'),modal=document.getElementById('orderModal');
 if(form) form.noValidate=true;
 const money=v=>`${Math.max(0,Math.round(Number(v)||0)).toLocaleString('vi-VN')}Ä`;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
 const inputs=()=>[...document.querySelectorAll('.item-qty')];
 function summary(){const items=inputs().map(i=>({name:i.dataset.name||'MÃ³n',qty:Math.max(0,parseInt(i.value,10)||0),price:Math.max(0,parseInt(i.dataset.price,10)||0)})).filter(i=>i.qty);const subtotal=items.reduce((s,i)=>s+i.qty*i.price,0);const discount=subtotal?50000:0;const stoveFee=stove?.checked&&subtotal<399000?50000:0;const total=Math.max(0,subtotal+stoveFee-discount);const list=document.getElementById('summaryItemList');if(list)list.innerHTML=items.length?items.map(i=>`<div class="summary-line summary-item"><span>${esc(i.name)} Ã ${i.qty}<small>${money(i.price)} / mÃ³n</small></span><strong>${money(i.qty*i.price)}</strong></div>`).join(''):'<p class="summary-empty">ChÆ°a cÃ³ mÃ³n nÃ o ÄÆ°á»£c chá»n.</p>';const sub=document.getElementById('summarySubtotal');if(sub)sub.textContent=money(subtotal);const d=document.getElementById('summaryDiscount');if(d)d.textContent=discount?`-${money(discount)}`:'0Ä';const f=document.getElementById('summaryStoveFee');if(f)f.textContent=stove?.checked?(stoveFee?money(stoveFee):'0Ä (miá»n phÃ­)'):'KhÃ´ng mÆ°á»£n báº¿p';const t=document.getElementById('totalPrice');if(t)t.textContent=money(total);return{items,subtotal,discount,stoveFee,total};}
 function setQty(i,n){i.value=Math.max(0,n);const b=document.getElementById(`badge-${i.id}`);if(b){b.textContent=i.value;b.classList.toggle('has-count',n>0)}}
 document.addEventListener('click',e=>{const b=e.target.closest('.btn-minus,.btn-plus');if(b){e.preventDefault();const i=document.getElementById(b.dataset.target);if(i){setQty(i,(parseInt(i.value,10)||0)+(b.classList.contains('btn-plus')?1:-1));summary()}return}const card=e.target.closest('.set-card');if(card&&!e.target.closest('button,input,a')){const i=card.querySelector('.item-qty');if(i){inputs().forEach(x=>{if(x!==i)setQty(x,0)});setQty(i,1);summary()}}});document.addEventListener('change',e=>{if(e.target.matches('.item-qty,#addonStove'))summary()});
 const close=()=>modal?.classList.remove('active');document.getElementById('closeModal')?.addEventListener('click',close);modal?.addEventListener('click',e=>{if(e.target===modal)close()});summary();if(!form)return;
 form.addEventListener('submit',async e=>{e.preventDefault();const value=id=>(document.getElementById(id)?.value||'').trim(),name=value('custName'),phone=value('custPhone'),email=value('custEmail'),address=value('custAddress'),s=summary();if(!name||!phone||!address)return alert('Vui lÃ²ng Äiá»n há» tÃªn, sá» Äiá»n thoáº¡i vÃ  Äá»a chá».');if(!s.items.length)return alert('Vui lÃ²ng chá»n Ã­t nháº¥t má»t mÃ³n hoáº·c má»t set.');const submit=form.querySelector('button[type="submit"]');if(submit)submit.disabled=true;try{const orderCode=`LN-${Math.floor(1000+Math.random()*9000)}`;const endpoint=new URL('/api/send-order',document.baseURI).toString();const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cust_name:name,cust_phone:phone,cust_email:email,cust_address:address,order_code:orderCode,items:s.items,stove_included:stove ? stove.checked === true : false})}),result=await r.json().catch(()=>({}));if(!r.ok||!result.success)throw Error(result.error||`HTTP ${r.status}`);const displayedCode=result.order_code||result.orderId||orderCode;document.getElementById('modalName').textContent=name;document.getElementById('modalAddress').textContent=address;const codeElement=document.getElementById('modalOrderCode')||document.getElementById('orderCodeDisplay')||document.getElementById('orderCode');if(codeElement)codeElement.textContent=`MÃ£ ÄÆ¡n hÃ ng: ${displayedCode}`;modal?.classList.add('active')}catch(err){console.error('Send order error:',err);alert('Xin lá»i, ÄÆ¡n hÃ ng chÆ°a ÄÆ°á»£c gá»­i. Vui lÃ²ng kiá»m tra káº¿t ná»i vÃ  thá»­ láº¡i sau.')}finally{if(submit)submit.disabled=false}})
});