'use strict';

const DISCOUNT = 50000;
const STOVE_FEE = 50000;
const FREE_THRESHOLD = 399000;
const NOTIFY_TIMEOUT_MS = 3500;
const GOOGLE_APPS_SCRIPT_URL = process.env.GOOGLE_APPS_SCRIPT_URL || process.env.GOOGLE_SHEET_URL || 'https://script.google.com/macros/s/AKfycbySw5rlJ_JjIKahh6XFjSLn8-WhEzpbXZBnuMvpfbPBWSckmVzBVbaztiHrieIdfakm/exec';
const json = (res, status, body) => res.status(status).json(body);
const str = (v, max) => String(v ?? '').trim().slice(0, max);
const vnd = v => new Intl.NumberFormat('vi-VN').format(Math.max(0, Number(v) || 0)) + 'đ';
const timestamp = () => { const p = new Intl.DateTimeFormat('en-GB', { timeZone: 'Asia/Saigon', hour: '2-digit', minute: '2-digit', second: '2-digit', day: '2-digit', month: '2-digit', year: 'numeric', hour12: false }).formatToParts(new Date()).reduce((a, x) => (a[x.type] = x.value, a), {}); return `${p.hour}:${p.minute}:${p.second} ${p.day}/${p.month}/${p.year}`; };
function calc(raw, stove) { const items = Array.isArray(raw) ? raw : []; if (!items.length) throw Error('Items are required'); let subtotal = 0; const normalized = items.slice(0, 50).map(i => { const name = str(i?.name, 120), qty = Number(i?.qty), price = Number(i?.price); if (!name || !Number.isSafeInteger(qty) || qty < 1 || !Number.isSafeInteger(price) || price < 0) throw Error('Invalid item'); subtotal += qty * price; return { name, qty, price }; }); const stoveFee = stove && subtotal < FREE_THRESHOLD ? STOVE_FEE : 0; return { items: normalized, subtotal, stoveFee, total: Math.max(0, subtotal + stoveFee - DISCOUNT) }; }
function payload(o) { const code = o.orderCode.startsWith('#') ? o.orderCode : `#LN-${o.orderCode.replace(/^LN-/, '')}`; const items = o.items.map(i => `${i.qty}x ${i.name} (${vnd(i.price * i.qty)})`).join('; '); const stove = o.stoveFee > 0 ? 'Có mượn bếp' : 'Không mượn bếp'; const total = vnd(o.total); const row = [o.createdAt, code, o.name, o.phone, o.email, o.address, items, stove, total, 'Chờ xác nhận']; return { row, rowData: row, values: row, data: row, timestamp: o.createdAt, time: o.createdAt, order_code: code, orderId: code, order_id: code, ma_don_hang: code, name: o.name, customer_name: o.name, cust_name: o.name, phone: o.phone, customer_phone: o.phone, cust_phone: o.phone, email: o.email, customer_email: o.email, address: o.address, customer_address: o.address, items, item_details: items, stove, stove_included: stove, total, total_price: total, status: 'Chờ xác nhận' }; }
function message(o) { const p = payload(o); return `Đơn hàng ${p.order_code}\nKhách: ${o.name}\nSĐT: ${o.phone}\nEmail: ${o.email || '-'}\nĐịa chỉ: ${o.address}\nMón: ${p.items}\nTổng: ${p.total}`; }
async function post(url, body, headers = {}) { if (!url) return { skipped: true }; const r = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body), redirect: 'follow', signal: AbortSignal.timeout(NOTIFY_TIMEOUT_MS) }); if (!r.ok) throw Error(`HTTP ${r.status}`); return { ok: true }; }
async function sendGoogleSheet(o) { return post(GOOGLE_APPS_SCRIPT_URL, payload(o), { 'Content-Type': 'text/plain;charset=utf-8', Accept: 'application/json' }); }
async function sendTelegram(o) { const token = process.env.TELEGRAM_BOT_TOKEN; const chatId = process.env.TELEGRAM_CHAT_ID; if (!token || !chatId) return { skipped: true }; return post(`https://api.telegram.org/bot${token}/sendMessage`, { chat_id: chatId, text: message(o) }); }
async function sendEmail(o) { if (!process.env.SMTP_HOST || !process.env.SMTP_USER || !process.env.SMTP_PASS || !process.env.ORDER_EMAIL_TO) return { skipped: true }; const nodemailer = require('nodemailer'); const transporter = nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: process.env.SMTP_SECURE === 'true', auth: { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }, connectionTimeout: NOTIFY_TIMEOUT_MS, greetingTimeout: NOTIFY_TIMEOUT_MS, socketTimeout: NOTIFY_TIMEOUT_MS }); return Promise.race([transporter.sendMail({ from: process.env.ORDER_EMAIL_FROM || process.env.SMTP_USER, to: process.env.ORDER_EMAIL_TO, subject: `Đơn hàng ${o.orderCode}`, text: message(o) }), new Promise((_, reject) => setTimeout(() => reject(Error('SMTP timeout')), NOTIFY_TIMEOUT_MS))]); }
module.exports = async (req, res) => { res.setHeader('Access-Control-Allow-Origin', '*'); if (req.method === 'OPTIONS') return res.status(204).end(); if (req.method !== 'POST') return json(res, 405, { success: false, error: 'Method Not Allowed' }); try { const b = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {}); const o = { ...calc(b.items, b.stove_included === true || b.stove === true), name: str(b.name || b.customer_name || b.cust_name || b.ten_khach_hang || b.customerName, 100), phone: str(b.phone || b.customer_phone || b.cust_phone || b.so_dien_thoai || b.customerPhone, 30), email: str(b.email || b.customer_email || b.cust_email || b.customerEmail, 254), address: str(b.address || b.customer_address || b.cust_address || b.dia_chi || b.customerAddress, 300), orderCode: str(b.order_code || b.orderId || b.order_id || b.ma_don_hang || b.code, 30) || String(Date.now()).slice(-4) }; if (!o.name || !o.phone || !o.address) throw Error('Customer information is required'); o.createdAt = timestamp(); const results = await Promise.allSettled([sendGoogleSheet(o), sendTelegram(o), sendEmail(o)]); const failures = results.filter(r => r.status === 'rejected'); if (failures.length) console.error('Order notification failures:', failures.map(r => r.reason?.message || r.reason)); return json(res, 200, { success: true, orderId: o.orderCode, order_code: o.orderCode, notifications: results.map(r => r.status === 'fulfilled' ? 'ok' : 'failed') }); } catch (e) { return json(res, 400, { success: false, error: e.message }); } };
